#### Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basic of Numpy, focusing on arrays and vectorized operations.

In [4]:
!pip install numpy

In [5]:
import numpy as np

## Create array using numpy
## Create a ID array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
## 1 d array
arr2 = np.array([1,2,3,4,5])
## Reshape to 2 d array
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([1,2,3,4,5])

print("Original (1D):")
print("array:", arr2)
print("shape:", arr2.shape, "ndim:", arr2.ndim)

print("\nReshaped (1,5):")
print("array:\n", arr2.reshape(1,5))
print("shape:", arr2.reshape(1,5).shape, " ndim:", arr2.reshape(1,5).ndim)

print("\nReshaped (5,1):")
print("array:\n", arr2.reshape(5,1))
print("shape:", arr2.reshape(5,1).shape, "ndim:", arr2.reshape(5,1).ndim)

Original (1D):
array: [1 2 3 4 5]
shape: (5,) ndim: 1

Reshaped (1,5):
array:
 [[1 2 3 4 5]]
shape: (1, 5)  ndim: 2

Reshaped (5,1):
array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
shape: (5, 1) ndim: 2


In [ ]:
## 2D array
arr2 = np.array([[1,2,3,4,5]])
print(f"arr2 shape: {arr2.shape}")
print(f"arr2 dimension: {arr2.ndim}")

arr2 shape: (1, 5)
arr2 dimension: 2


In [11]:
## 2D array - more examples
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(f"arr2 shape: {arr2.shape}")
print(f"arr2 dimensions: {arr2.ndim}")

[[1 2 3 4 5]
 [2 3 4 5 6]]
arr2 shape: (2, 5)
arr2 dimensions: 2


In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
print(np.arange(0,10,2))
print(f"shape: {np.arange(0,10,2).shape}")
print(f"dimension: {np.arange(0,10,2).ndim}")
print("\nReshaping to Column Vector (5,1)")
print(np.arange(0,10,2).reshape(5,1))
print(f"shape: {np.arange(0,10,2).reshape(5,1).shape}")
print(f"dimension: {np.arange(0,10,2).reshape(5,1).ndim}")
print("\nReshaping to Row Vector (1,5)")
print(np.arange(0,10,2).reshape(1,5))
print(f"shape: {np.arange(0,10,2).reshape(1,5).shape}")
print(f"dimension: {np.arange(0,10,2).reshape(1,5).ndim}")

[0 2 4 6 8]
shape: (5,)
dimension: 1

Reshaping to Column Vector (5,1)
[[0]
 [2]
 [4]
 [6]
 [8]]
shape: (5, 1)
dimension: 2

Reshaping to Row Vector (1,5)
[[0 2 4 6 8]]
shape: (1, 5)
dimension: 2


In [31]:
np.ones((0,3))

array([], shape=(0, 3), dtype=float64)

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones((1,3))

array([[1., 1., 1.]])

In [34]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
## Atrributes of Numpy Array

arr = np.array([[1,2,3],[4,5,6]])

print("Arr:\n", arr)
print("Shape:", arr.shape) # Output: (2,3)
print("Number of dimensions: ", arr.ndim) # output: 2
print("Size (number of elements): ", arr.size) # output: 6
print("Data type:", arr.dtype) # Ouput: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Arr:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type: int64
Item size (in bytes): 8


In [43]:
### Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element wise addition
print("Addition: ", arr1+arr2)

### Element wise substraction
print("Substraction: ", arr1-arr2)

### Element wise multiplication
print("Multiplication: ", arr1 * arr2)

### Element wise division
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [46]:
## Universal Function

arr = np.array([2,3,4,5,6])

### Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [49]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print (arr[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr[1:3][:1]

array([[5, 6, 7, 8]])

In [57]:
arr[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [58]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [64]:
print(arr[0][0])
print(arr[0,0])
print(arr[0:1][0])
print(arr[0:1,0])

1
1
[1 2 3 4]
[1]


In [65]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
## arr[0][0]
print("arr[0][0]:", arr[0][0])

## arr[0,0]
print("arr[0,0]:", arr[0,0])

## arr[0:1][0]
print("arr[0:1][0]:", arr[0:1][0])

## arr[0:1, 0]
print("arr[0:1,0]:", arr[0:1,0])


arr[0][0]: 0
arr[0,0]: 0
arr[0:1][0]: [0 1 2 3]
arr[0:1,0]: [0]


In [78]:
arr[0:1,0]

array([0])

In [88]:
### 3D - Array (3D Tensor)
arr = np.array([
                [[1, 2], [3, 4]],    # First matrix
                [[5, 6], [7, 8]],    # Second matrix
                [[9,10], [11,12]]    # Third matrix
                ])

print("Array:\n",arr)
print("Shape: ",arr.shape)
print("Dimensions: ",arr.ndim)
print("Size: ",arr.size)
print("Items: ",arr.itemsize)
print("Data type: ",arr.dtype)

Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape:  (3, 2, 2)
Dimensions:  3
Size:  12
Items:  8
Data type:  int64


In [96]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [97]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [99]:
arr[1:] = 100
print(arr)

[[100   1   2   3]
 [100 100 100 100]
 [100 100 100 100]]


In [104]:
### Statistial Concepts - Normalization
### To have a mean(avg) of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [106]:
print("Mean of normalized data: ", np.mean(normalized_data))
print("Std of normalized data: ", np.std(normalized_data))

Mean of normalized data:  0.0
Std of normalized data:  0.9999999999999999


In [107]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [116]:
### Logical Operation
data = np.arange(1,11,1)

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])